/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package parcial1.vista;

/**
 *
 * @author Usuario
 */
public class ExportarReporteDialog extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ExportarReporteDialog.class.getName());

    /**
     * Creates new form ExportarReporteDialog
     */
    public ExportarReporteDialog() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoFormato = new javax.swing.ButtonGroup();
        jPanelExportarReporte = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rbPDF = new javax.swing.JRadioButton();
        rbCSV = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        txtNombreArchivo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtRuta = new javax.swing.JTextField();
        btnExaminar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        chkResumen = new javax.swing.JCheckBox();
        chkDatos = new javax.swing.JCheckBox();
        chkPoblaciones = new javax.swing.JCheckBox();
        chkResultado = new javax.swing.JCheckBox();
        btnCancelar = new javax.swing.JButton();
        btnExportar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Exportar Reporte");

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel1.setText("Formato del archivo:");

        grupoFormato.add(rbPDF);
        rbPDF.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        rbPDF.setSelected(true);
        rbPDF.setText("PDF");

        grupoFormato.add(rbCSV);
        rbCSV.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        rbCSV.setText("CSV");

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel2.setText("Nombre del archivo:");

        txtNombreArchivo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombreArchivo.setText("reporte_simulacion");

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel3.setText("Ubicación:");

        txtRuta.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnExaminar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnExaminar.setText("Examinar");
        btnExaminar.addActionListener(this::btnExaminarActionPerformed);

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setText("Contenido incluido:");

        chkResumen.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        chkResumen.setText("Resumen general");

        chkDatos.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        chkDatos.setText("Datos de la simulación");

        chkPoblaciones.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        chkPoblaciones.setText("Poblaciones finales");

        chkResultado.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        chkResultado.setText("Resultado y causa de finalización");

        btnCancelar.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");

        btnExportar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnExportar.setText("Exportar");

        javax.swing.GroupLayout jPanelExportarReporteLayout = new javax.swing.GroupLayout(jPanelExportarReporte);
        jPanelExportarReporte.setLayout(jPanelExportarReporteLayout);
        jPanelExportarReporteLayout.setHorizontalGroup(
            jPanelExportarReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelExportarReporteLayout.createSequentialGroup()
                .addGroup(jPanelExportarReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelExportarReporteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rbPDF)
                        .addGap(114, 114, 114)
                        .addComponent(rbCSV)
                        .addGap(32, 32, 32))
                    .addGroup(jPanelExportarReporteLayout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addGroup(jPanelExportarReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelExportarReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(txtRuta))
                        .addGap(18, 18, 18)))
                .addComponent(btnExaminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelExportarReporteLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(jPanelExportarReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelExportarReporteLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(308, 308, 308))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelExportarReporteLayout.createSequentialGroup()
                        .addGroup(jPanelExportarReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCancelar)
                            .addGroup(jPanelExportarReporteLayout.createSequentialGroup()
                                .addComponent(chkResumen)
                                .addGap(18, 18, 18)
                                .addComponent(chkDatos)))
                        .addGroup(jPanelExportarReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelExportarReporteLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(chkPoblaciones)
                                .addGap(18, 18, 18)
                                .addComponent(chkResultado))
                            .addGroup(jPanelExportarReporteLayout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(btnExportar)))
                        .addGap(37, 37, 37))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelExportarReporteLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(313, 313, 313))
        );
        jPanelExportarReporteLayout.setVerticalGroup(
            jPanelExportarReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExportarReporteLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanelExportarReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbPDF)
                    .addComponent(rbCSV))
                .addGap(18, 18, 18)
                .addGroup(jPanelExportarReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelExportarReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExaminar))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelExportarReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkResumen)
                    .addComponent(chkDatos)
                    .addComponent(chkPoblaciones)
                    .addComponent(chkResultado))
                .addGap(61, 61, 61)
                .addGroup(jPanelExportarReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnExportar))
                .addContainerGap(227, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelExportarReporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelExportarReporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExaminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExaminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExaminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ExportarReporteDialog().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExaminar;
    private javax.swing.JButton btnExportar;
    private javax.swing.JCheckBox chkDatos;
    private javax.swing.JCheckBox chkPoblaciones;
    private javax.swing.JCheckBox chkResultado;
    private javax.swing.JCheckBox chkResumen;
    private javax.swing.ButtonGroup grupoFormato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanelExportarReporte;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton rbCSV;
    private javax.swing.JRadioButton rbPDF;
    private javax.swing.JTextField txtNombreArchivo;
    private javax.swing.JTextField txtRuta;
    // End of variables declaration//GEN-END:variables
}
