/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package parcial1.vista;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import parcial1.dao.ReporteDAO;
import parcial1.dao.ReporteDAOImpl;
import parcial1.modelo.ReporteSimulacion;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableRowSorter;
import java.io.FileOutputStream;
import java.io.OutputStreamWriter;
import java.io.BufferedWriter;
import java.nio.charset.StandardCharsets;
import java.io.IOException;

/**
 *
 * @author Usuario
 */
public class SimulacionesGuardadas extends javax.swing.JFrame {
    
    private final ReporteDAO reporteDAO;
    private TableRowSorter<DefaultTableModel> sorter;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SimulacionesGuardadas.class.getName());

    /**
     * Creates new form SimulacionesGuardadas
     */
    public SimulacionesGuardadas() {
        initComponents();

        reporteDAO = new ReporteDAOImpl();
        setLocationRelativeTo(null);
        cargarReportes();
        sorter = new TableRowSorter<>(
        (DefaultTableModel) tblReportes1.getModel()
    );

tblReportes1.setRowSorter(sorter);

txtBuscar.getDocument().addDocumentListener(new DocumentListener() {

    @Override
    public void insertUpdate(DocumentEvent e) {
        filtrar();
    }

    @Override
    public void removeUpdate(DocumentEvent e) {
        filtrar();
    }

    @Override
    public void changedUpdate(DocumentEvent e) {
        filtrar();
    }
});
cmbResultado.addActionListener(e -> filtrar());
}

private void cargarReportes() {

    DefaultTableModel modeloTabla =
            (DefaultTableModel) tblReportes1.getModel();

    modeloTabla.setRowCount(0);

    List<ReporteSimulacion> reportes = reporteDAO.listar();

    for (ReporteSimulacion reporte : reportes) {

        modeloTabla.addRow(new Object[]{
            reporte.getId(),
            reporte.getNombre(),
            reporte.getFecha(),
            reporte.getResultado(),
            reporte.getTurnos(),
            reporte.getPlantas(),
            reporte.getConejos(),
            reporte.getLobos()
        });
    }

    lblCantidad.setText(
            reportes.size() + " simulaciones encontradas"
    );
}

private void filtrar() {

    String textoBuscar = txtBuscar.getText().trim();
    String resultadoSeleccionado =
            cmbResultado.getSelectedItem().toString();

    java.util.List<RowFilter<Object, Object>> filtros =
            new java.util.ArrayList<>();

    if (!textoBuscar.isEmpty()) {

        filtros.add(
                RowFilter.regexFilter(
                        "(?i)" + java.util.regex.Pattern.quote(textoBuscar)
                )
        );
    }

    if (!resultadoSeleccionado.equals("Todos")) {

        filtros.add(
                RowFilter.regexFilter(
                        "^" + java.util.regex.Pattern.quote(resultadoSeleccionado) + "$",
                        3
                )
        );
    }

    if (filtros.isEmpty()) {

        sorter.setRowFilter(null);

    } else {

        sorter.setRowFilter(
                RowFilter.andFilter(filtros)
        );
    }

    lblCantidad.setText(
            tblReportes1.getRowCount()
                    + " simulaciones encontradas"
    );
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
//<editor-fold defaultstate="collapsed" desc="comment">
@SuppressWarnings("unchecked")
//</editor-fold>
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSimulacionesGuardadas = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cmbResultado = new javax.swing.JComboBox<>();
        tblReportes = new javax.swing.JScrollPane();
        tblReportes1 = new javax.swing.JTable();
        btnVerReporte = new javax.swing.JButton();
        btnExportar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        lblCantidad = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Simulaciones Guardadas");

        lblBuscar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblBuscar.setText("Buscar:");

        txtBuscar.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel1.setText("Resultado:");

        cmbResultado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Estable", "Sin plantas", "Sin conejos", "Sin lobos", "Colapso" }));

        tblReportes1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Fecha", "Resultado", "Turnos", "Plantas", "Conejos", "Lobos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblReportes.setViewportView(tblReportes1);

        btnVerReporte.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnVerReporte.setText("Ver Reporte");
        btnVerReporte.addActionListener(this::btnVerReporteActionPerformed);

        btnExportar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnExportar.setText("Exportar");
        btnExportar.addActionListener(this::btnExportarActionPerformed);

        btnEliminar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnVolver.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(this::btnVolverActionPerformed);

        lblCantidad.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        lblCantidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCantidad.setText("0 simulaciones encontradas");

        javax.swing.GroupLayout jPanelSimulacionesGuardadasLayout = new javax.swing.GroupLayout(jPanelSimulacionesGuardadas);
        jPanelSimulacionesGuardadas.setLayout(jPanelSimulacionesGuardadasLayout);
        jPanelSimulacionesGuardadasLayout.setHorizontalGroup(
            jPanelSimulacionesGuardadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSimulacionesGuardadasLayout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(jPanelSimulacionesGuardadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanelSimulacionesGuardadasLayout.createSequentialGroup()
                        .addGroup(jPanelSimulacionesGuardadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBuscar)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelSimulacionesGuardadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbResultado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtBuscar)))
                    .addComponent(tblReportes, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelSimulacionesGuardadasLayout.createSequentialGroup()
                        .addComponent(btnVerReporte)
                        .addGap(39, 39, 39)
                        .addComponent(btnExportar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar)
                        .addGap(45, 45, 45)
                        .addComponent(btnVolver))
                    .addComponent(lblCantidad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(136, 136, 136))
        );
        jPanelSimulacionesGuardadasLayout.setVerticalGroup(
            jPanelSimulacionesGuardadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSimulacionesGuardadasLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelSimulacionesGuardadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelSimulacionesGuardadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tblReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelSimulacionesGuardadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerReporte)
                    .addComponent(btnExportar)
                    .addComponent(btnEliminar)
                    .addComponent(btnVolver))
                .addGap(18, 18, 18)
                .addComponent(lblCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSimulacionesGuardadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSimulacionesGuardadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int filaSeleccionada = tblReportes1.getSelectedRow();

    if (filaSeleccionada == -1) {

        JOptionPane.showMessageDialog(
                this,
                "Seleccione un reporte para eliminar.",
                "Sin selección",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    int confirmacion = JOptionPane.showConfirmDialog(
            this,
            "¿Está seguro de que desea eliminar el reporte seleccionado?",
            "Confirmar eliminación",
            JOptionPane.YES_NO_OPTION
    );

    if (confirmacion == JOptionPane.YES_OPTION) {

        int id = Integer.parseInt(
                tblReportes1.getValueAt(filaSeleccionada, 0).toString()
        );

        reporteDAO.eliminar(id);

        cargarReportes();

        JOptionPane.showMessageDialog(
                this,
                "Reporte eliminado correctamente."
        );
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnVerReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerReporteActionPerformed
        int filaSeleccionada = tblReportes1.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(
                    this,
                    "Seleccione una simulación para ver el reporte.",
                    "Sin selección",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        String id = tblReportes1.getValueAt(filaSeleccionada, 0).toString();
        String nombre = tblReportes1.getValueAt(filaSeleccionada, 1).toString();
        String fecha = tblReportes1.getValueAt(filaSeleccionada, 2).toString();
        String resultado = tblReportes1.getValueAt(filaSeleccionada, 3).toString();
        String turnos = tblReportes1.getValueAt(filaSeleccionada, 4).toString();
        String plantas = tblReportes1.getValueAt(filaSeleccionada, 5).toString();
        String conejos = tblReportes1.getValueAt(filaSeleccionada, 6).toString();
        String lobos = tblReportes1.getValueAt(filaSeleccionada, 7).toString();

        String mensaje =
                "REPORTE DE SIMULACIÓN\n\n"
                + "ID: " + id + "\n"
                + "Nombre: " + nombre + "\n"
                + "Fecha: " + fecha + "\n"
                + "Resultado: " + resultado + "\n"
                + "Turnos ejecutados: " + turnos + "\n"
                + "Plantas vivas: " + plantas + "\n"
                + "Conejos vivos: " + conejos + "\n"
                + "Lobos vivos: " + lobos;

        JOptionPane.showMessageDialog(
                this,
                mensaje,
                "Detalle del reporte",
                JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_btnVerReporteActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        int filaSeleccionada = tblReportes1.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(
                    this,
                    "Seleccione una simulación para exportar.",
                    "Sin selección",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        JFileChooser selectorArchivo = new JFileChooser();
        selectorArchivo.setDialogTitle("Guardar reporte CSV");
        selectorArchivo.setSelectedFile(
                new File("reporte_simulacion.csv")
        );

        int opcion = selectorArchivo.showSaveDialog(this);

        if (opcion != JFileChooser.APPROVE_OPTION) {
            return;
        }

        File archivo = selectorArchivo.getSelectedFile();

        if (!archivo.getName().toLowerCase().endsWith(".csv")) {
            archivo = new File(
                    archivo.getAbsolutePath() + ".csv"
            );
        }

        try (BufferedWriter escritor = new BufferedWriter(
        new OutputStreamWriter(
                new FileOutputStream(archivo),
                StandardCharsets.UTF_8
        )
)) {
            // Permite que Excel reconozca correctamente UTF-8
            escritor.write('\uFEFF');

            escritor.write(
             "ID;Nombre;Fecha;Resultado;Turnos;Plantas;Conejos;Lobos\n"
            );

            for (int columna = 0; columna < tblReportes1.getColumnCount(); columna++) {

                Object valor = tblReportes1.getValueAt(
                        filaSeleccionada,
                        columna
                );

                String texto = valor == null
                        ? ""
                        : valor.toString();

                texto = texto.replace("\"", "\"\"");

                escritor.write("\"" + texto + "\"");

                if (columna < tblReportes1.getColumnCount() - 1) {
                    escritor.write(";");
                }
            }

            escritor.write("\n");

            JOptionPane.showMessageDialog(
                    this,
                    "Reporte exportado correctamente en:\n"
                            + archivo.getAbsolutePath(),
                    "Exportación completada",
                    JOptionPane.INFORMATION_MESSAGE
            );

        } catch (IOException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "No se pudo exportar el reporte.\n"
                            + e.getMessage(),
                    "Error de exportación",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnExportarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SimulacionesGuardadas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnVerReporte;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cmbResultado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelSimulacionesGuardadas;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JScrollPane tblReportes;
    private javax.swing.JTable tblReportes1;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
